[Earth_param]
g=9.80616 #The gravitational constant of the earth
M_e=5.9742e24 # The mass of the earth
omega=7.292e-5 #rotation speed of the erath
k_hydro=0.934 # 
G=6.67408e-11 # Gravitational constant
a = 6371000 # Earth radius
C=8.034e37
k_f=0.942

[Model_param]
maxdeg=128 # degree of the spherical harmonics used
k_max=10 # number of convergence of The SL equation resolution
epsilon=1 # minimal error for the SL equation resolution
topo_it_max=10 # maximum iteration for the convergence of topography loop
del_topo=0.1 # minimal error of the topography

[Input_data]
data_way='C:/Users/ahenry01/Desktop/Python_code/SL_C0de_data'
ice_way='ice6g_data'
topo_way='topo_SL'
sed_way='Irrawady_sedimentationgrid'
love_way='VM5.l40.um316.lm5.1024'

[Time]
time_step=[26,25,24,23,22,21,20.5,20,19.5,19,18.5,18,17.5,17,16.5,16,15.5,15,14.5,14,13.5,13,12.5,12,11.5,11,10.5,10,9.5,9,8.5,8,7.5,7,6.5,6,5.5,5,4.5,4,3.5,3,2.5,2,1.5,1,0.5,0]